version: "3.7"

services:

  traefik:
    image: "traefik:v2.5"
    restart: unless-stopped
    container_name: "traefik"
    command:
      - "--entrypoints.web.address=:8080"
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.directory=/etc/traefik/conf.d/"
      - "--api.dashboard=true"
      - "--certificatesresolvers.myresolver.acme.email=${LETSENCRYPT_USER}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      #- "--certificatesresolvers.myresolver.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=${LE_DNS_PROVIDER}"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.delayBeforeCheck=10"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53,salvador.porkbun.com:53,curitiba.porkbun.com:53"
      - "--pilot.token=${TRAEFIK_PILOT_TOKEN}"
      #- "--log.level=DEBUG"
    ports:
      - "8080:8080"
      - "443:443"
    environment:
      - PORKBUN_API_KEY
      - PORKBUN_SECRET_API_KEY
      - BASE_DOMAIN
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "./config:/etc/traefik/conf.d/"

  echo:
    image: pierrezemb/gostatic
    restart: unless-stopped
    ports:
      - "8043:8043"
    volumes:
      - "./echo:/srv/http"
