# http routing section
[http]
  [http.routers]
     # Define a connection between requests and services
     [http.routers.to-nas]
        rule = "Host(`nas.{{env "BASE_DOMAIN"}}`)"
        # If the rule matches, forward to the nas service (declared below)
        service = "synology"
        [http.routers.to-nas.tls]
          certResolver = "myresolver"

  [http.services]
    [http.services.synology.loadBalancer]
      [[http.services.synology.loadBalancer.servers]]
        url = "http://monzon:5000/"

# TCP routing for cloud station
[tcp]
  [tcp.routers]
    [tcp.routers.to-cloud-station]
      entryPoints = ["cloud-station"]
      rule = "HostSNI(`nas.{{env "BASE_DOMAIN"}}`)"
      service = "cloud-station"

  [tcp.services]
    [[tcp.services.cloud-station.loadBalancer.servers]]
      address = "monzon:6690"
